const CATEGORIES_TRANSLATION = {
    type: "Type",
    licence: "Licence",
    price: "Price",
    cc: "C.C.",
    year: "Year",
    km: "Mileage",
    brand: "Brand",
};

const TYPES_TRANSLATION = {
    classic: "Classic",
    custom: "Custom",
    maxiScooter: "Maxi-Scooter",
    naked: "Naked",
    offRoad: "Off-Road",
    scooter: "Scooter",
    sport: "Sport",
    touring: "Touring",
    trail: "Trail",
    tresRuedas: "Three Wheels",
};

const BRANDS_TRANSLATION = {
    aprilia: "Aprilia",
    benelli: "Benelli",
    bmw: "BMW",
    brixton: "Brixton",
    cake: "Cake",
    cfmoto: "CF Moto",
    daelim: "Daelim",
    derbi: "Derbi",
    ducati: "Ducati",
    fantic: "Fantic",
    fbMondial: "FB Mondial",
    fkMotors: "FK Motors",
    fkm: "FKM",
    gasGas: "Gas Gas",
    gilera: "Gilera",
    goes: "Goes",
    hanway: "Hanway",
    harleyDavidson: "Harley Davidson",
    honda: "Honda",
    husaberg: "Husaberg",
    husqvarna: "Husqvarna",
    indian: "Indian",
    kawasaki: "Kawasaki",
    keeway: "Keeway",
    ktm: "KTM",
    kymco: "Kymco",
    lml: "LML",
    macbor: "Macbor",
    mash: "Mash",
    mitt: "Mitt",
    motoGuzzi: "Moto Guzzi",
    motorHispania: "Motor Hispania",
    mvAgusta: "MV Agusta",
    orcal: "Orcal",
    peugeot: "Peugeot",
    piaggio: "Piaggio",
    quadro: "Quadro",
    rieju: "Rieju",
    royalEnfield: "Royal Enfield",
    suzuki: "Suzuki",
    swm: "SWM",
    sym: "SYM",
    triumph: "Triumph",
    um: "UM",
    vespa: "Vespa",
    voge: "Voge",
    yamaha: "Yamaha",
    zontes: "Zontes",
};

const LICENCES_TRANSLATION = { a: "A", a1b: "A1/B", a2: "A2", am: "AM" };

export { CATEGORIES_TRANSLATION, TYPES_TRANSLATION, BRANDS_TRANSLATION, LICENCES_TRANSLATION };
